#!/bin/bash
# from ~/Dropbox/write/darkness/darkroomretreat

# collect images
cd ../yodrew.github.io/img
rsync -auv book-cover.png ../../darkroomretreat/manuscript/images/title_page.png
rsync -auv photo/*.jpg ../../darkroomretreat/manuscript/images
# rsync -auv photo/book/*.jpg ../../darkroomretreat/manuscript/images
rsync -auv plan/image/*.png ../../darkroomretreat/manuscript/images
rsync -auv plan/image/book/*.png ../../darkroomretreat/manuscript/images
# text


  # collect
cd darkroomretreat/manuscript
cp blurb.md <(echo) notes.md <(echo) foreword.md <(echo) preface.md <(echo) introduction.md <(echo) hygiene.md <(echo) darkroom-retreat.md <(echo) psychology.md <(echo) format.md <(echo) protocol.md <(echo) prepare.md <(echo) design.md <(echo) make.md <(echo) air.md <(echo) darkness.md <(echo) water.md <(echo) faq.md <(echo) bibliography-influences.md <(echo) acknowledgments.md <(echo) services.md <(echo) license.md <(echo) bio.md ../../cat/cat.md
cd ../../cat
  # YAML
cd ..perl -p -i -e 's,---\n,,s' *.md
perl -p -i -e 's,title:,#,s' *.md
perl -i -nle 'print if !/layout:/' *.md
perl -i -nle 'print if !/permalink:/' *.md
perl -i -nle 'print if !/navprev:/' *.md
perl -i -nle 'print if !/navnext:/' *.md
  # header hashmarks
sed -i 's/^####/##/g' *.md
  # miscellaneous
sed -i 's/ {at} /@/g' bio.md license.md
sed -i 's,](/about,](/bio,g' license.md prepare.md
  # superscript
sed -i 's,<sup>,^,g' *.md 
sed -i 's,</sup>,^,g' *.md
  #links
  # underline
perl -p -i -e 's,(^|[^!])\[([^^!\]]+)\]\(,\1\[____\2____\]\(,g' *.md
    # image
perl -pi -e 's,\]\(/img/plan/image/,\]\(images/,g' *.md
perl -pi -e 's,[a-z:\, ]+\]\(/img/photo/,\]\(images/,g' *.md
    # cross
      # /chapter#section to #section
perl -p -i -e 's,\]\(\/(notes|foreword|preface|introduction|hygiene|darkroom-retreat|psychology|format|protocol|prepare|design|make|air|darkness|water|faq|bibliography-influences|acknowledgments|services|license|bio)#,\]\(#,g' *.md
      # /chapter to #chapter
perl -p -i -e 's,\]\(\/(notes|foreword|preface|introduction|hygiene|darkroom-retreat|psychology|format|protocol|prepare|design|make|air|darkness|water|faq|bibliography-influences|acknowledgments|services|license|bio)\),\]\(#$1\),g' *.md
      # (/ to (http://darkroomretreat
perl -p -i -e 's,\(\/,\(http:\/\/darkroomretreat.com\/,g' *.md
  # anchors
    # generate
perl -p -i -e 's/^(#+ )([1-9]+ )*(- )?([A-Za-z0-9 ,_-]+)/\1\2\3\4 \{#\4\}/g' *.md
    # fix
		# misc
perl -pi -e 's/{#relief, rest, recovery}/{#relief rest recovery}/g' blurb.md
		# duplicates
# remove dashes in titles: perl -p -i -e 's,\{#([^\}-]+)- ,\{#$1,g' *.md
perl -pi -e '$a=1 if(!$a && s/{#constraints}/{#constraints-ventilation}/);' air.md
perl -pi -e '$a=1 if(!$a && s/{#constraints}/{#constraints-lightproof}/);' air.md
perl -pi -e 's/{#power}/{#power-air}/g' air.md
perl -pi -e '$a=1 if(!$a && s/{#constraints}/{#constraints-sleeping-mask}/);' darkness.md
perl -pi -e '$a=1 if(!$a && s/{#constraints}/{#constraints-blind}/);' darkness.md
perl -pi -e 's/{#mechanics}/{#mechanics-faq}/g' faq.md
perl -pi -e 's/{#darkness}/{#darkness-darkroom-retreat}/g' darkroom-retreat.md
perl -pi -e 's/{#attitude}/{#attitude-darkroom-retreat}/g' darkroom-retreat.md
perl -pi -e 's/{#mechanics}/{#mechanics-darkroom-retreat}/g' darkroom-retreat.md
perl -pi -e 's/{#food}/{#food-darkroom-retreat}/g' darkroom-retreat.md
perl -pi -e 's/{#hygiene}/{#hygiene-introduction}/g' introduction.md
perl -pi -e 's/{#mechanics}/{#mechanics-protocol}/g' protocol.md
perl -pi -e 's/{#food}/{#food-protocol}/g' protocol.md
perl -pi -e 's/{#attitude}/{#attitude-protocol}/g' protocol.md
perl -pi -e 's/{#power}/{#power-protocol}/g' protocol.md
perl -pi -e '$a=1 if(!$a && s/{#basic}/{#basic-sink}/);' water.md
perl -pi -e '$a=1 if(!$a && s/{#upgrade}/{#upgrade-sink}/);' water.md
perl -pi -e '$a=1 if(!$a && s/{#basic}/{#basic-toilet}/);' water.md
perl -pi -e '$a=1 if(!$a && s/{#upgrade}/{#upgrade-toilet}/);' water.md
perl -pi -e '$a=1 if(!$a && s/{#basic}/{#basic-shower}/);' water.md
perl -pi -e '$a=1 if(!$a && s/{#upgrade}/{#upgrade-shower}/);' water.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
perl -p -i -e 's,\{#([^ \}]+) ,\{#$1-,g' *.md
  # line breaks
  # end message
echo -book done

